# Generated by Django 5.2.1 on 2025-08-15 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='category',
            field=models.CharField(blank=True, choices=[('breakfast', 'Breakfast'), ('lunch', 'Lunch'), ('dinner', 'Dinner'), ('dessert', 'Desserts'), ('appetizer', 'Appetizers'), ('snack', 'Snacks'), ('italian', 'Italian'), ('asian', 'Asian'), ('mexican', 'Mexican'), ('indian', 'Indian'), ('mediterranean', 'Mediterranean'), ('american', 'American'), ('vegetarian', 'Vegetarian'), ('vegan', 'Vegan'), ('gluten-free', 'Gluten-Free'), ('keto', 'Keto'), ('healthy', 'Healthy'), ('quick', 'Quick & Easy')], max_length=20, null=True),
        ),
    ]
