# Generated by Django 5.2.1 on 2025-08-08 19:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('interactions', '0003_follow'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterUniqueTogether(
            name='comment',
            unique_together=set(),
        ),
    ]
